# Generated by Django 5.2.4 on 2025-10-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_issue_student_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='hide_identity',
            field=models.BooleanField(default=False),
        ),
    ]
